### ISSUE TITLE
Starcraft SC2Replay data reading problem

### ISSUE THREAD

**Issue by zy5037** [liuruoze/mini-AlphaStar#10]
I downloaded the replay data according to the tutorial and extracted it into ".SC2Replay" format. However, the run.py file is not read properly and gives the following error

Traceback (most recent call last):
  File "/home/czy/Documents/network/reforcement/mini-AlphaStar-main/alphastarmini/core/sl/dataset_pickle.py", line 140, in get_trainable_data
    traj_dict = pickle.load(handle)
_pickle.UnpicklingError: invalid load key, '\x1b'.

Does the downloaded data require additional pre-processing?

**Comment by liuruoze** [comment]
Hi, would you please show me more information?

Have you tried only give one replay for training? Or can you open that replay by the SC2.exe to view it? 

It comes that the replay data may be broken, but we should first check that the replay is right, the replay can be view, and the replay version is matching.

**Comment by agi1512** [comment]
You may want to try to add `encoding='utf-8'` to the `open(...)` statement. May fix your problem (fixed for me)

**Comment by liuruoze** [comment]
If there are no more new problems, I will first close this issue. If you find any new questions, you can open up the issue at any time.
