### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by khcf123** [liuruoze/mini-AlphaStar#19]
In run.py, I run codes below:

# # 6. we use SL model and replays to do reinforcement learning
    from alphastarmini.core.rl import rl_train_with_replay
    rl_train_with_replay.test(on_server=P.on_server, replay_path=P.replay_path)

And the outcome is shown below with error:

(torch_1_5) PS C:\Users\alexa\Downloads\mini-AlphaStar-main> python run.py
pygame 2.1.2 (SDL 2.0.18, Python 3.7.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
run init
cudnn available
cudnn version 7604
start_time before training: 2022-01-22 13:00:03
map name: AbyssalReef
player.name: MainPlayer
opponent.name: MainPlayer
player.race: Race.protoss
opponent.race: Race.protoss
start_time before reset: 2022-01-22 13:01:34
total_episodes: 1
replay_path: C:/Program Files (x86)/StarCraft II/Replays_small/fffeb9b9437fde426b5e51a700bd339e0eedb127a2106ff9920b65c2bccfd4f4.SC2Replay
start_episode_time before is_final: 2022-01-22 13:03:07
ActorLoop.run() Exception cause return, Detials of the Exception: get_baseline_state_from_multi_source_state() missing 1 required positional argument: 'msstate'
Traceback (most recent call last):
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\rl\actor_plus_z.py", line 279, in run
    baseline_state = self.player.agent.agent_nn.get_baseline_state_from_multi_source_state(state)
TypeError: get_baseline_state_from_multi_source_state() missing 1 required positional argument: 'msstate'

run over

Please help me, thanks!!

**Comment by liuruoze** [comment]
Hi, this is due to that the "actor_plus_z" is a deprecated version for the new RL training method. 

In the master version, we have provided the new RL training script in "rl_vs_inner_bot_mp" (which is a new multi-processing plus multi-thread training way, increasing the training speed by 10x). 

Could you wait for some days? A new version of mAS will come soon. We think you can directly use the new version (because it is more accurate and much faster, making you save much time) than be familiar with the older version of codes.

**Comment by khcf123** [comment]
Of course I can wait! Thanks for the reply!

**Comment by liuruoze** [comment]
@khcf123 Hi, the v_1.07 is published, you can find the introduction to use the new training pattern of reinforcement learning in "https://github.com/liuruoze/mini-AlphaStar/tree/v_1.07". Have a good time and good luck!

**Comment by khcf123** [comment]
Thanks again!! Highly appreciated!

**Comment by khcf123** [comment]
Hi again, I already use v_1.07 and when i run following codes in run.py:

from alphastarmini.core.sl import sl_train_by_tensor
    sl_train_by_tensor.test(on_server=P.on_server)

The outcome is shown below with error:

len(train_set) 125
len(val_set) 125
len(train_loader) 63
len(val_loader) 63
pygame 2.1.2 (SDL 2.0.18, Python 3.7.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame 2.1.2 (SDL 2.0.18, Python 3.7.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "run.py", line 57, in <module>
    sl_train_by_tensor.test(on_server=P.on_server)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_tensor.py", line 548, in test
    main_worker(DEVICE)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_tensor.py", line 226, in main_worker
    val_set, batch_iter, epoch, val_loader)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_train_by_tensor.py", line 261, in train
    train=True)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\sl_loss_multi_gpu.py", line 193, in get_sl_loss_for_tensor
    state = Feature.feature2state(features)
  File "C:\Users\alexa\Downloads\mini-AlphaStar-main\alphastarmini\core\sl\feature.py", line 158, in feature2state
    assert feature_1_size + feature_2_size + feature_3_size == feature.shape[1]
AssertionError

Please help me, thanks!!

**Comment by liuruoze** [comment]
Hi, this problem has been fixed, please check that (the newest tag of v_1.07 published in today).

**Comment by liuruoze** [comment]
Hi, if there are no problems now, I will close this issue. If you find your problems are not solved, you can re-open this issue at any time.
