### ISSUE TITLE
What version of replays?

### ISSUE THREAD

**Issue by doncha88** [liuruoze/mini-AlphaStar#2]
Hello, please tell me which version of the replays should be loaded into the data folder?

**Comment by liuruoze** [comment]
https://github.com/Blizzard/s2client-proto#downloads 
Yes, it's here, please download the replay pack for 3.16.1.

**Comment by doncha88** [comment]
Thanks, which episode is preferable? PvP or PvT?

**Comment by liuruoze** [comment]
The two ones are both useable. The selection may depend on the setting of RL training you want to use. E.g., if you prefer self-play, you should choose PvP replays. On the contrary, if you only intend to train against the built-in AI, you can choose the PvT replays.

**Comment by doncha88** [comment]
Thanks
