### ISSUE TITLE
Multi node training

### ISSUE THREAD

**Issue by agi1512** [liuruoze/mini-AlphaStar#20]
Hello

Do you plan to make it possible to train agent on multiple nodes? I mean on computers that are divided by network. Maybe in form of a league like in original DeepMind paper

**Comment by liuruoze** [comment]
Hi, due to that we don't have multi machines at now, we will not try them now. However, we will try to start multi processes to train a league in one single common machine. This may be the feature of the next several versions.

**Comment by liuruoze** [comment]
Hi, if there are no problems now, I will close this issue. If you find your problems are not solved, you can re-open this issue at any time.
