### ISSUE TITLE
Trained model replays.

### ISSUE THREAD

**Issue by rahatsantosh** [liuruoze/mini-AlphaStar#22]
Once, I have trained the model, how do I run a game against it say by either a bot or human opponent. I'm unable to figure out how to run the custom agent. Any ideas on how this can be done?

**Comment by liuruoze** [comment]
Yes, you can use the "rl_vs_inner_bot_mp.py" to play vs. the built-in bot by the trained model.

**Comment by liuruoze** [comment]
Hi, I will close this issue if you don't have new questions. You can always re-open it if you think the problem is not resolved.
