### ISSUE TITLE
Issue with result reproduction

### ISSUE THREAD

**Issue by rahatsantosh** [liuruoze/mini-AlphaStar#25]
I have run the algorithm for around more than 30 days on an NVIDIA DGX server, with the configuration of 500GB RAM and 8 Tesla GPUs with 32 GB VRAM each. The algorithm still seems to be losing all the matches against the level 2 difficulty bot. 
The source code has been used from the mini-AlphaStar repo, version 1.07, on SC2 game version 4.10.0. 
Kindly advise me on how to proceed with respect to the same. 
Link to the output logs for the latest batch of RL training against the level 2 bot - [https://learnermanipal-my.sharepoint.com/:u:/g/personal/rahat_santosh1_learner_manipal_edu/EVi0z-QKI19Ogh8LK8PnbloB6xEdedXNc7_a-AMuTDejOQ?e=bwQRzr](https://learnermanipal-my.sharepoint.com/:u:/g/personal/rahat_santosh1_learner_manipal_edu/EVi0z-QKI19Ogh8LK8PnbloB6xEdedXNc7_a-AMuTDejOQ?e=bwQRzr)

**Comment by liuruoze** [comment]
I found out why. The version you are using is 4.10.0. This newer version has a big gap from version 3.16.1. I'm not sure what version of replay you are training with (you may not be using the 90 replays we provide). But if you follow the way below, you should be able to reproduce our results.

1. Using version 3.16.1；
2. Use the SL model we provide；
3. On the basis of the SL model, through RL training, using 15 processes (on 8 GPU cards), 2 threads in each process, and training for 3 days, you can get an agent with a higher winning rate (more than 50%)  against level-2 built-in bot.

**Comment by rahatsantosh** [comment]
Ok, thanks, will try that too. Though will the algorithm be affected, I mean I used 4.10.0 for the dataset and changed the version in the repo to 4.10 too. Are there some architectural changes that might be needed for the algorithm, for it to perform on 4.10 version.

**Comment by rahatsantosh** [comment]
Its working with version 3.16.1. Giving a win rate of 45%.
Thanks for the help.
