### ISSUE TITLE
Unable to process action with ability_id: xxxx

### ISSUE THREAD

**Issue by mlx3223mlx** [liuruoze/mini-AlphaStar#26]
您好，我在运行这段代码时
![code](https://user-images.githubusercontent.com/74055742/174463268-ca83a455-b951-4a6b-8390-efdc3cd31d65.png)
出现了如下的问题
![result](https://user-images.githubusercontent.com/74055742/174463305-7cd42403-df7d-4e98-8c91-e8ef1b2e247e.png)
我使用的sc2版本为3.16.1，replay文件是您在Useful-Big-Resources中提供的，系统为ubuntu20.04。请问这个问题该怎么解决呢？

**Comment by liuruoze** [comment]
这个Unable to process action with ability_id: xxxx应该是不影响程序运行的。

如果觉得这个信息显示麻烦的话，需要到pysc2源文件里去把这个提示注释掉。

**Comment by mlx3223mlx** [comment]
好的，谢谢！我再看一下。
