### ISSUE TITLE
SL Training Results?

### ISSUE THREAD

**Issue by johnrachwan123** [liuruoze/mini-AlphaStar#3]
Hello, 

Great job on this repo! I was wondering if you have any results of the model against bots? Such as winrate for example or sample replays.

Thanks!

**Comment by liuruoze** [comment]
Hi, thank you very much for your attention.

We have done some experiments based on mini-AlphaStar, such as first using supervised learning to train, and then using reinforcement learning to continue training. The relevant training results have been summarized in a future work to be published. When the review results come out, we will update the information immediately.

**Comment by johnrachwan123** [comment]
Thank you!
