### ISSUE TITLE
Missing relu activation functions.

### ISSUE THREAD

**Issue by dachidahu** [liuruoze/mini-AlphaStar#4]
https://github.com/liuruoze/mini-AlphaStar/blob/04f755bab0840d0de510ea086a95f59f22ca211b/alphastarmini/core/arch/spatial_encoder.py#L73-L75

Hi Liuruoze,
Thank you for the amazing work. I found your code is kind different from what stated in detailed-architecture.txt. Is there a reason to omit the relu between convolution layers?  Also I have checked the very similar implemtation from Tencent.  https://github.com/dachidahu/SC2AgentsZoo2/blob/1300af878cab00d16b0f266753b10acdbfee0bbc/agent_TLeagueFormal14/TPolicies/tpolicies/net_zoo/mnet_v6/utils.py#L408-L412.
As you can see the relu is applied for each of convolution layer. (relu is default activation function in tensorflow 1.15 https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/contrib/layers/conv2d)

Thanks.

**Comment by liuruoze** [comment]
Thanks for your question. Your description is clear and exact. I think I understood your problem rightly. Actually, there is truly a description in spatial encoder: "then downsampled from 128x128 to 16x16 through 3 2D convolutions and ReLUs ". Here really have Relus. I don't remember why I don't have a ReLU after ds_1, ds_2, and ds_3. Maybe I didn't notice the text of "ReLUs". Or maybe something else. At now, don't consider other things, I think we should add the ReLU after each conv2d. I confirmed that PyTorch conv2d does not have default ReLU. And the default function for TensorFlow 1.15 is ReLU (thanks for your resource!). So here should be added 3 ReLUs, each after one conv2d. We will do a quick fix, and the update will be made in the main branch and the next release version. Thanks for your reminders and corrections! 

If so, can you help me confirm another case? That is in line 189 of the Location head, AlphaStar says "Afterwards, it is upsampled 2x by each of a series of transposed 2D convolutions". Here, I don't seem to see the description of Relu. However, what I implemented in the code is to add a Relu after each upsample, like "x = F.relu(self.us_1(x))". Whether my adjustment is correct, could you give some reference suggestions? If these are not needed, I will delete these Relus. Thank you in advance.

**Comment by liuruoze** [comment]
Hi,  @dachidahu  I close this issue now. If you find any other questions, please feel free to reopen this issue.
