### ISSUE TITLE
种族的选取

### ISSUE THREAD

**Issue by ZHQ-air** [liuruoze/mini-AlphaStar#5]
在test_alphastar_replay.py文件中，设置使用‘Terran’，
run_alphastar_replay(on_server=on_server, race_name='Terran')
但“An Introduction of mini-AlphaStar”论文中说的是只能使用'Protoss'。这里是不是应该按照论文中所说：设置种族为'Protoss'
run_alphastar_replay(on_server=on_server, race_name='Protoss')
非常感谢！！

**Comment by liuruoze** [comment]
test_alphastar_replay.py这个文件是用来分析AlphaStar的replay的，所以使用任何种族都可以。An Introduction of mini-AlphaStar这篇论文虽然说的是我们训练的是神族，但其实本方法可以改造为三个种族都可以训练。只是我们在后续的工作中会只专注于神族vs神族的训练（包括我们之后会放出来的训练细节等（这些正在review过程中，暂时无法公开，不过我可以提供指引））。

**Comment by liuruoze** [comment]
如果没有其它问题，这个issue我先关了。其它问题可以在另一个issue里，或者有需要的话再起一个新的issue来讨论。
