### ISSUE TITLE
代码的运行

### ISSUE THREAD

**Issue by ZHQ-air** [liuruoze/mini-AlphaStar#6]
运行run.py后出错，终端提示如下：
File "/home/zhq/Doctor/RL_Project/mini-AlphaStar/alphastarmini/core/sl/test_alphastar_replay.py", line 192, in run_alphastar_replay
    replay_files = os.listdir(REPLAY_PATH)
FileNotFoundError: [Errno 2] No such file or directory: './data/Replays/replays_paper_ready/Final/Protoss/'

我已经把StarCraftII/Replays文件夹放入了mini-AlphaStar/data文件夹中，但依然找不到相应的路径，请问下“Replays/replays_paper_ready/Final/Protoss/”   回放的数据我能怎么获得呢？

**Comment by liuruoze** [comment]
run.py里

#from alphastarmini.core.sl import transform_replay_data
# transform_replay_data.test(on_server=False)

#from alphastarmini.core.sl import sl_train_by_pickle
# sl_train_by_pickle.test(on_server=P.on_server)

其实应该从上面两个代码开始训练：1个是把data文件夹下的replay转换成tensor或pickle，1个是开始监督学习训练。把它们反注释就可以用了。

而test_alphastar_replay其实是有其它的用处，是我们之前研究时用来分析AlphaStar的replay用的，本身不在训练环节之内。

你如果有其它问题的话，欢迎再提issue，我看到后会及时回复

**Comment by ZHQ-air** [comment]
好的，我明白了。非常感谢您的及时回复，也非常感谢您开源的代码，以后会跟着您的代码深入学习的。

**Comment by ZHQ-air** [comment]
我还要一个疑问，就是transform_replay_data.py文件中的test(on_server=False)函数中，定义了REPLAY_PATH="data/Replays/filtered_replays_1/"，这里的filtered_replays_1文件夹中存放的回访文件是指定某一个种族的回放文件还是就是官方的 Replays 文件中存放的所有回放数据啊？

**Comment by liuruoze** [comment]
这个是过滤后的数据，例如，我们只选择PvP，且只在一个地图下的数据。这样的话数据量就能大大减少了。

**Comment by ZHQ-air** [comment]
好的，我再看看，多谢啦
